// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"context"
)

// MutationResolver is the query root resolver
type MutationResolver interface {
	TriggerIngest(ctx context.Context, provider string, regions []string) (*IngestRun, error)
}

// QueryResolver is the query root resolver
type QueryResolver interface {
	FindNode(ctx context.Context, label string, id string) (*Node, error)
	WalkEdges(ctx context.Context, start string, edgeTypes []string, direction string, depth int) ([]*NodeRef, error)
	PathFinder(ctx context.Context, start string, end string, edgePattern []string, maxHops int) ([]*Path, error)
	BlastRadius(ctx context.Context, node string, depth int) ([]*NodeRef, error)
	Subgraph(ctx context.Context, center string, radius int) (*Subgraph, error)
	IngestStatus(ctx context.Context, runID string) (*IngestRun, error)
	Healthz(ctx context.Context) (string, error)
}

// ResolverRoot is the root resolver interface
type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

// NewExecutableSchema is a compatibility function with gqlgen
func NewExecutableSchema(cfg interface{}) interface{} {
	return nil
}
