// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Mutation struct {
}

type Query struct {
}

type NodeRef struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

type Node struct {
	ID         string `json:"id"`
	Label      string `json:"label"`
	Properties *string `json:"properties"`
}

type Edge struct {
	From       string `json:"from"`
	To         string `json:"to"`
	Type       string `json:"type"`
	Properties *string `json:"properties"`
}

type Path struct {
	Nodes  []NodeRef `json:"nodes"`
	Edges  []Edge `json:"edges"`
	Length int `json:"length"`
}

type Subgraph struct {
	Center NodeRef   `json:"center"`
	Nodes  []NodeRef `json:"nodes"`
}

type IngestService struct {
	Name      string `json:"name"`
	Status    string `json:"status"`
	NodeCount int `json:"nodeCount"`
	EdgeCount int `json:"edgeCount"`
	Error     *string `json:"error"`
}

type IngestRun struct {
	ID        string           `json:"id"`
	Status    string `json:"status"`
	StartedAt string `json:"startedAt"`
	Services  []IngestService  `json:"services"`
}
