package graphql

import (
	"encoding/json"
	"fmt"
)

// This file will not be regenerated automatically.
//
// It serves as dependency injection for your app, add any dependencies you require
// here.

type Resolver struct {
	ffi FFIClient
}

// NewResolver creates a new Resolver with the given FFI client.
func NewResolver(ffi FFIClient) *Resolver {
	return &Resolver{ffi: ffi}
}

// The type definitions are now in models_generated.go (auto-generated by gqlgen)

// FindNode resolves the findNode query.
func (r *Resolver) FindNode(label, id string) (*Node, error) {
	result, err := r.ffi.QueryFindNode(label, id)
	if err != nil {
		return nil, fmt.Errorf("query find node failed: %w", err)
	}

	if result == "null" {
		return nil, nil
	}

	var nodeRef NodeRef
	if err := json.Unmarshal([]byte(result), &nodeRef); err != nil {
		return nil, fmt.Errorf("failed to parse node response: %w", err)
	}

	return &Node{
		ID:    nodeRef.ID,
		Label: nodeRef.Label,
	}, nil
}

// WalkEdges resolves the walkEdges query.
func (r *Resolver) WalkEdges(start string, edgeTypes []string, direction string, depth int) ([]*NodeRef, error) {
	result, err := r.ffi.QueryWalkEdges(start, edgeTypes, direction, uint32(depth))
	if err != nil {
		return nil, fmt.Errorf("query walk edges failed: %w", err)
	}

	var nodes []NodeRef
	if err := json.Unmarshal([]byte(result), &nodes); err != nil {
		return nil, fmt.Errorf("failed to parse walk edges response: %w", err)
	}

	// Convert to pointers
	result_ptrs := make([]*NodeRef, len(nodes))
	for i := range nodes {
		result_ptrs[i] = &nodes[i]
	}

	return result_ptrs, nil
}

// PathFinder resolves the pathFinder query.
func (r *Resolver) PathFinder(start, end string, edgePattern []string, maxHops int) ([]*Path, error) {
	result, err := r.ffi.QueryPathFinder(start, end, edgePattern, uint32(maxHops))
	if err != nil {
		return nil, fmt.Errorf("query path finder failed: %w", err)
	}

	var paths []Path
	if err := json.Unmarshal([]byte(result), &paths); err != nil {
		return nil, fmt.Errorf("failed to parse path finder response: %w", err)
	}

	// Convert to pointers
	result_ptrs := make([]*Path, len(paths))
	for i := range paths {
		result_ptrs[i] = &paths[i]
	}

	return result_ptrs, nil
}

// BlastRadius resolves the blastRadius query.
func (r *Resolver) BlastRadius(node string, depth int) ([]*NodeRef, error) {
	result, err := r.ffi.QueryBlastRadius(node, uint32(depth))
	if err != nil {
		return nil, fmt.Errorf("query blast radius failed: %w", err)
	}

	var nodes []NodeRef
	if err := json.Unmarshal([]byte(result), &nodes); err != nil {
		return nil, fmt.Errorf("failed to parse blast radius response: %w", err)
	}

	// Convert to pointers
	result_ptrs := make([]*NodeRef, len(nodes))
	for i := range nodes {
		result_ptrs[i] = &nodes[i]
	}

	return result_ptrs, nil
}

// Subgraph resolves the subgraph query.
func (r *Resolver) Subgraph(center string, radius int) (*Subgraph, error) {
	result, err := r.ffi.QuerySubgraph(center, uint32(radius))
	if err != nil {
		return nil, fmt.Errorf("query subgraph failed: %w", err)
	}

	var sg Subgraph
	if err := json.Unmarshal([]byte(result), &sg); err != nil {
		return nil, fmt.Errorf("failed to parse subgraph response: %w", err)
	}

	return &sg, nil
}

// IngestStatus resolves the ingestStatus query.
func (r *Resolver) IngestStatus(runID string) (*IngestRun, error) {
	result, err := r.ffi.IngestStatus(runID)
	if err != nil {
		return nil, fmt.Errorf("ingest status failed: %w", err)
	}

	if result == "" {
		return nil, nil
	}

	var run IngestRun
	if err := json.Unmarshal([]byte(result), &run); err != nil {
		return nil, fmt.Errorf("failed to parse ingest run response: %w", err)
	}

	return &run, nil
}

// Healthz resolves the healthz query.
func (r *Resolver) Healthz() (string, error) {
	result, err := r.ffi.HealthCheck()
	if err != nil {
		return "error", fmt.Errorf("health check failed: %w", err)
	}
	return result, nil
}
