package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"
)

// TriggerIngest is the resolver for the triggerIngest field.
func (r *mutationResolver) TriggerIngest(ctx context.Context, provider string, regions []string) (*IngestRun, error) {
	return r.Resolver.TriggerIngest(provider, regions)
}

// FindNode is the resolver for the findNode field.
func (r *queryResolver) FindNode(ctx context.Context, label string, id string) (*Node, error) {
	return r.Resolver.FindNode(label, id)
}

// WalkEdges is the resolver for the walkEdges field.
func (r *queryResolver) WalkEdges(ctx context.Context, start string, edgeTypes []string, direction string, depth int) ([]*NodeRef, error) {
	return r.Resolver.WalkEdges(start, edgeTypes, direction, depth)
}

// PathFinder is the resolver for the pathFinder field.
func (r *queryResolver) PathFinder(ctx context.Context, start string, end string, edgePattern []string, maxHops int) ([]*Path, error) {
	return r.Resolver.PathFinder(start, end, edgePattern, maxHops)
}

// BlastRadius is the resolver for the blastRadius field.
func (r *queryResolver) BlastRadius(ctx context.Context, node string, depth int) ([]*NodeRef, error) {
	return r.Resolver.BlastRadius(node, depth)
}

// Subgraph is the resolver for the subgraph field.
func (r *queryResolver) Subgraph(ctx context.Context, center string, radius int) (*Subgraph, error) {
	return r.Resolver.Subgraph(center, radius)
}

// IngestStatus is the resolver for the ingestStatus field.
func (r *queryResolver) IngestStatus(ctx context.Context, runID string) (*IngestRun, error) {
	return r.Resolver.IngestStatus(runID)
}

// Healthz is the resolver for the healthz field.
func (r *queryResolver) Healthz(ctx context.Context) (string, error) {
	return r.Resolver.Healthz()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
