apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activable.fullname" . }}
  labels:
    {{- include "activable.labels" . | nindent 4 }}
data:
  db-host: {{ include "activable.database.host" . }}
  db-port: {{ .Values.database.port | quote }}
  db-name: {{ .Values.database.name }}
  db-user: {{ .Values.database.user }}
  graph-name: {{ .Values.graph.name }}
