apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activable.fullname" . }}
  labels:
    {{- include "activable.labels" . | nindent 4 }}
data:
  ACTIVABLE_DB_HOST: {{ .Values.database.host | quote }}
  ACTIVABLE_DB_PORT: {{ .Values.database.port | quote }}
  ACTIVABLE_DB_NAME: {{ .Values.database.name | quote }}
  ACTIVABLE_DB_USER: {{ .Values.database.user | default "activable" | quote }}
  ACTIVABLE_DB_PASSWORD: {{ .Values.database.password | default "activable" | quote }}
  ACTIVABLE_GRAPH_NAME: {{ .Values.graphql.graphName | quote }}
  ACTIVABLE_MAX_CONNECTIONS: {{ .Values.database.maxConnections | default 20 | quote }}
  RUST_LOG: {{ .Values.graphql.logLevel | default "info" | quote }}
  PORT: {{ .Values.graphql.port | quote }}
  {{- if .Values.localstack.enabled }}
  AWS_ENDPOINT_URL: "http://{{ include "activable.fullname" . }}-localstack:4566"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_DEFAULT_REGION: {{ .Values.localstack.region | default "us-east-1" | quote }}
  {{- end }}
