apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activable.fullname" . }}
  labels:
    {{- include "activable.labels" . | nindent 4 }}
data:
  db.host: {{ .Values.database.host | quote }}
  db.port: {{ .Values.database.port | quote }}
  db.name: {{ .Values.database.name | quote }}
  db.max_connections: {{ .Values.database.maxConnections | default 20 | quote }}
  graph.name: {{ .Values.graphql.graphName | quote }}
  log.level: {{ .Values.graphql.logLevel | quote }}
  server.port: {{ .Values.graphql.port | quote }}
