apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activable.fullname" . }}
  labels:
    {{- include "activable.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc | quote }}
